<?php /**
 *@copyright : ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 *@author	 : Shiv Charan Panjeta < shiv@toxsl.com >
 */
 

return [
	"message" => [
		"add" => [
			"Message[message]" => "This is autogenerated test description.

					This is autogenerated test description.

					This is autogenerated test description.
",
			"Message[session_id]" => "1",
			"Message[state_id]" => "0",
			"Message[booking_id]" => "1",
			"Message[type_id]" => "0",
			"Message[to_id]" => "1",
			"Message[send_time]" => "2017-07-18 17:49:02",
			"Message[from_id]" => "1",
			"Message[created_on]" => "2017-07-18 17:49:02",
			"Message[updated_on]" => "2017-07-18 17:49:02",
			"Message[created_by_id]" => "1",
			],
		"update?id={id}"=>  [
			"Message[message]" => "This is autogenerated test description.

					This is autogenerated test description.

					This is autogenerated test description.
",
			"Message[session_id]" => "1",
			"Message[state_id]" => "0",
			"Message[booking_id]" => "1",
			"Message[type_id]" => "0",
			"Message[to_id]" => "1",
			"Message[send_time]" => "2017-07-18 17:49:02",
			"Message[from_id]" => "1",
			"Message[created_on]" => "2017-07-18 17:49:02",
			"Message[updated_on]" => "2017-07-18 17:49:02",
			"Message[created_by_id]" => "1",
			],
		"index" => [],
		"get?id={}" => [],
		"delete?id={}" => []
	]
];
?>
