<?php /**
 *@copyright : ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 *@author	 : Shiv Charan Panjeta < shiv@toxsl.com >
 */
 

return [
	"page" => [
		"add" => [
			"Page[title]" => "Test string",
			"Page[description]" => "This is autogenerated test description.

					This is autogenerated test description.

					This is autogenerated test description.
",
			"Page[state_id]" => "0",
			"Page[type_id]" => "0",
			"Page[created_on]" => "2017-06-22 10:59:34",
			"Page[updated_on]" => "2017-06-22 10:59:34",
			"Page[created_by_id]" => "1",
			],
		"update?id={id}"=>  [
			"Page[title]" => "Test string",
			"Page[description]" => "This is autogenerated test description.

					This is autogenerated test description.

					This is autogenerated test description.
",
			"Page[state_id]" => "0",
			"Page[type_id]" => "0",
			"Page[created_on]" => "2017-06-22 10:59:34",
			"Page[updated_on]" => "2017-06-22 10:59:34",
			"Page[created_by_id]" => "1",
			],
		"index" => [],
		"get?id={}" => [],
		"delete?id={}" => []
	]
];
?>
